Add Date input for table filter
inventree/InvenTree pull request #4067
Opened 2022-12-15 16:08 UTC by Bbillyben

Add a 'date' field to be processed in table filter.

This will report a naive date to the server. This needs to be 'timezoned' before being processed into queryset.

table filter definition would be like : 
```
date_field:{
                title: '{% trans "Date Field" %}',
                type: 'date'
            },
```

Any though on this? Any evident drawbacks I missed ?

2022-12-15 20:44 UTC, SchrodingersGat commented
This looks nice! Do you have any particular fields in mind to query with this?

2022-12-15 21:47 UTC, Bbillyben commented
Not in the core, even if I'm pretty we could find some utility,   but I'm implenting it in my plugins.
The goal is to filter on specific timeframe or date, to export directly relevant data regarding our quality processes (deeply stringent).

2022-12-20 12:25 UTC, Bbillyben commented
I've added date filtering on expiry date in stock item table in stocklocation tab.
=> I haven't found a way to get the user timezone properly

pre-commit issue reference the first 'import datetime' on line 3 as unused, I had to remove it to passe QC.

2022-12-20 12:36 UTC, wolflu05 commented
> => I haven't found a way to get the user timezone properly

Are you searching for a way to get the client's timezone in javascript? This should work like described here: https://stackoverflow.com/a/1091399

2022-12-20 21:53 UTC, matmair commented
@Bbillyben I would suggest doing all client timezone things on the client - that is really messy/error-prone serverside.

2022-12-23 10:42 UTC, Bbillyben commented
Ok, got it, 

I moved to store timezoned timestamp from js and process the timestamp in py.

Is that better?

2023-01-03 15:03 UTC, Bbillyben commented
As far as I can see it's working without raising any warnings. (so i turn check it ready for review)

I haven't go through build, purchase order and sales there should be something interesting to implement with the different dates (dates, target date, completion dates, ....)

2023-01-03 21:07 UTC, SchrodingersGat commented
@Bbillyben can you explain the reasoning behind using integer dates rather than say an ISO datestring i.e. YYYY-MM-DD?

For example look at how we do filtering for the calendar display views.

Also, as the API has been updated, please bump the version in `InvenTree/api_version.py` :)

2023-01-03 22:46 UTC, matmair requested changes

2023-01-03 22:46 UTC, matmair commented on InvenTree/stock/api.py
> +                date_lte = datetime.fromtimestamp(int(expired_date_lte) / 1e3)
I would very much prefer passing UTC ISO dates here instead of timestamps. Requires less computation on the client side

2023-01-03 22:46 UTC, matmair commented on InvenTree/stock/api.py
> +                date_gte = datetime.fromtimestamp(int(expiry_date_gte) / 1e3)
Same as above

2023-01-04 08:43 UTC, Bbillyben commented
Thanks for your feed back. 

That was a mistake attempting to store a timezoned timestamp. I was assuming that integer are always better than string !

I've seen https://github.com/inventree/InvenTree/blob/8a095f00cf07dc8af5603643a658aed0a8cf71e1/InvenTree/build/models.py#L114
from build filter_queryset
https://github.com/inventree/InvenTree/blob/8a095f00cf07dc8af5603643a658aed0a8cf71e1/InvenTree/build/api.py#L137

Is that what you have pointed out @SchrodingersGat  ?

So as far as I can understand, dates are used (/stored?) in simple non extended ISO 8601 (aka YYYY-MM-DD), without any information on user timezone, inferring de facto a UTC date ?

I will the get back to my original commit (without the in-python timezoning) and add an exception's catching.

2023-01-04 10:50 UTC, matmair approved these changes

2023-01-04 19:48 UTC, SchrodingersGat approved these changes

2023-01-04 19:48 UTC, merged

2023-01-04 19:48 UTC, SchrodingersGat commented
Thanks for the contribution @Bbillyben