[FR] Simplify / optimize setting loading
inventree/InvenTree pull request #4152
Opened 2023-01-04 22:44 UTC by matmair

This PR adds a global config-file cache. Environment variables will still be read live to enable CI manipulation etc.

Fixes https://github.com/inventree/InvenTree/issues/4149

2023-01-05 15:03 UTC, matmair commented
@SchrodingersGat ready for review

2023-01-06 00:30 UTC, SchrodingersGat requested changes

2023-01-06 00:30 UTC, SchrodingersGat commented on InvenTree/InvenTree/config.py
> +        return CONIFG_DATA
spelling :)

2023-01-06 17:24 UTC, matmair commented on InvenTree/InvenTree/config.py
> +CONIFG_DATA = None
Fixed :+1

2023-01-07 12:24 UTC, SchrodingersGat approved these changes

2023-01-07 12:24 UTC, merged

2023-01-07 12:24 UTC, SchrodingersGat commented
Great work thanks @matmair