Fix for returning stock from the customer to a specified location
inventree/InvenTree pull request #4208
Opened 2023-01-13 16:47 UTC by bloemp

When returning stock from the customer, the allocations of that stock are freed. If the new stock location is the same as the parent stock, merge the stock back into the parent.

2023-01-13 18:09 UTC, miggland commented
I started a dev server with your branch - in my quick tests it seems to work.

2023-01-13 18:54 UTC, bloemp commented
That is good to hear, but stock handling is a complex thing and I'm still very new to python/django and InvenTree... so be careful and hopefully this patch gets through the QA process of @matmair  and @SchrodingersGat

2023-01-13 18:55 UTC, matmair approved these changes
Looks great @bloemp !

We won't merge for a few days as that is the maintainers prerogative. So if you want you could add a test for the merging of stock as a cherry on top.

2023-01-13 18:57 UTC, bloemp commented
Let me see if we can get that cherry, haven't written any tests yet... so this is another nice challenge.

2023-01-13 18:57 UTC, matmair commented
We would especially look for:
Carrying over of the notes
Removal of the old associations
An error if there is no parent - with the atomic change rolling back correctly

2023-01-14 17:05 UTC, bloemp commented
@matmair I think i've created tests for both allocateToCustomer and return_from_customer. I'm not quite sure how to implement "An error if there is no parent - with the atomic change rolling back correctly".
Any pointers you could give me? The return_from_customer function already checks for the parent being None so I'm not completely sure this test will work

2023-01-15 12:58 UTC, miggland commented
@bloemp: Not sure if it adds much, but should the original reason for my bug report be tested? Ie, check that the returned stock becomes available again?

2023-01-15 13:19 UTC, bloemp commented
@miggland that should already be tested by the added test. We are testing 2 situations:

1) The returned stock is returned to the original locatation (aka parent location) then it will be merged with the parent. We check if the amount of the parent is increased and the previous allocated stock record is removed. 
Because of the increased amount, the stock will be available

2) The returned stock is de-allocated to another stock location. The test checks to see if the references to customer, salesorder and ownedby fields are cleared and the new location is set. We also test that a stock track item is added with the correct status.
Because this stock record is no longer owned or allocated to a customer/salesorder it will be available as new stock.

So I think we have your original issue covered, but if you can think of more ways to check I will try to add it to the test.

2023-01-15 13:41 UTC, miggland commented
Especially your first point pretty much covers what I had in mind. I was thinking along the lines of counting the total available part stock before and after return, and to make sure the numbers make sense. However, I can't say that I've checked the logic in detail here so maybe that's a bit overkill/covered elsewhere.

2023-01-15 13:48 UTC, matmair approved these changes
Looks good to me, full coverage and sensible tests. I am delighted at this point. Your recent contributions are great and noticed @bloemp !
Testing full stock numbers might give some extra assurance as @miggland suggested.

2023-01-15 15:38 UTC, bloemp commented
Adding a total stock check is definitely a good catch, that why I've added a total stock check that compares the stock at the start and at the end of the remove_from_customer test.
This will hopefully ensure that all stock is returned.

2023-01-15 15:42 UTC, matmair requested changes
small typo

2023-01-15 15:42 UTC, matmair commented on InvenTree/stock/tests.py
> +        # Establish total stock for part after remove from customer to check that we stille have the correct quantity in stock
```suggestion
        # Establish total stock for the part after remove from customer to check that we still have the correct quantity in stock
```
typo :-)

2023-01-15 15:42 UTC, matmair commented on InvenTree/stock/tests.py
> +        # First establish total stock for thid part
```suggestion
        # First establish the total stock for this part
```

2023-01-15 15:59 UTC, bloemp commented on InvenTree/stock/tests.py
> +        # First establish total stock for thid part
Fixed

2023-01-15 16:32 UTC, matmair approved these changes

2023-01-15 16:32 UTC, matmair commented
@SchrodingersGat ready for merge

2023-01-24 22:33 UTC, SchrodingersGat approved these changes

2023-01-24 22:34 UTC, SchrodingersGat commented
@bloemp many thanks :)

2023-01-24 22:34 UTC, merged

2023-03-29 16:54 UTC, exp commented
This fix effectively corrupts existing databases by removing items the Sales Order. These sales orders appear as incoherent, showing a greater number of items shipped than are listed.


I believe in fact that this means there is now absolutely no record anywhere of the original product shipped to a customer. You can see individual items were shipped, but the only record is which customer, not which sales order.


I think this is really bad, I'm going to have to recover from a database backup to restore this tracking information, and for many production installs out there they may have completely lost this information now as the stock tracking deltas do not include the appropriate IDs.


Could someone please confirm my findings are accurate? I apologise for not contributing in the last year but we have indeed adopted Inventree on a large scale and I would like to be of use. Fixing this is now very high priority for us.

2023-03-29 18:40 UTC, matmair commented
The item is returned from the customer so it is merged back into stock. Not sure I see the problem.

2023-03-29 19:41 UTC, exp commented
Actually in the last day a couple of the problems have been fixed by the Return Orders merge. Stock tracking deltas now do include sales orders, but I can't see that this has been historically populated. That may pose a problem later on.

In addition, I believe the original Sales Order is still modified so there is no record a stock item was ever included (that I can find). I can't think of any reason a historical Sales Order should ever be modified. This is a real pain for auditing purposes and especially if you deal with many departments at a customer and now have no idea what you shipped to whom and when.

The way I would re-engineer this (and am happy to, I will also try and fill in a bunch of other issues ASAP) is to instead use the latest entry in the StockItemTracking to determine if something is assigned to an order, has been shipped to a customer, is in the process of RMA etc. I can't see that this has been done as part of the latest merge, but perhaps I missed it?

2023-03-30 02:50 UTC, SchrodingersGat commented
@exp I can see the issue here, I think I have a way to address this which also makes the salesorder process much simpler. Will get onto this ASAP, as returning via RMA does remove the item from the salesorder, which is a critical bug!

2023-03-30 08:42 UTC, exp commented
@SchrodingersGat Thank you. If there's anything I can do to assist please let me know. The Return Orders merge was incredibly timely as this problem was discovered in the last few days and then you immediately almost completely fixed it!

2023-03-30 12:30 UTC, SchrodingersGat commented
Ref: https://github.com/inventree/InvenTree/pull/4541